CREATE SCHEMA IF NOT EXISTS feifood;
SET search_path TO feifood;
CREATE TABLE usuario ( id SERIAL PRIMARY KEY, nome VARCHAR(120) NOT NULL, email VARCHAR(120) UNIQUE NOT NULL, senha_hash VARCHAR(255) NOT NULL, perfil VARCHAR(20) NOT NULL CHECK (perfil IN ('CLIENTE','ADMIN')), criado_em TIMESTAMP NOT NULL DEFAULT NOW());
CREATE TABLE estabelecimento ( id SERIAL PRIMARY KEY, nome VARCHAR(120) NOT NULL, cnpj VARCHAR(18), cidade VARCHAR(80), ativo BOOLEAN NOT NULL DEFAULT TRUE, criado_em TIMESTAMP NOT NULL DEFAULT NOW());
CREATE TABLE alimento ( id SERIAL PRIMARY KEY, estabelecimento_id INT NOT NULL REFERENCES estabelecimento(id) ON DELETE CASCADE, nome VARCHAR(120) NOT NULL, descricao TEXT, preco NUMERIC(10,2) NOT NULL CHECK (preco >= 0), tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('COMIDA','BEBIDA')), vegetariano BOOLEAN, teor_alcoolico NUMERIC(5,2), ativo BOOLEAN NOT NULL DEFAULT TRUE, criado_em TIMESTAMP NOT NULL DEFAULT NOW());
CREATE TABLE pedido ( id SERIAL PRIMARY KEY, usuario_id INT NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT, status VARCHAR(20) NOT NULL DEFAULT 'CRIADO', criado_em TIMESTAMP NOT NULL DEFAULT NOW(), atualizado_em TIMESTAMP);
CREATE TABLE pedido_item ( pedido_id INT NOT NULL REFERENCES pedido(id) ON DELETE CASCADE, alimento_id INT NOT NULL REFERENCES alimento(id) ON DELETE RESTRICT, quantidade INT NOT NULL CHECK (quantidade > 0), preco_unitario NUMERIC(10,2) NOT NULL CHECK (preco_unitario >= 0), PRIMARY KEY (pedido_id, alimento_id));
CREATE TABLE avaliacao ( pedido_id INT PRIMARY KEY REFERENCES pedido(id) ON DELETE CASCADE, estrelas INT NOT NULL CHECK (estrelas BETWEEN 0 AND 5), comentario TEXT, criado_em TIMESTAMP NOT NULL DEFAULT NOW());
CREATE INDEX idx_alimento_nome ON alimento (nome);
CREATE INDEX idx_usuario_email ON usuario (email);
